# -*- coding: utf-8 -*-
"""Nowcasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvRcbO0_kWpcce74F5laWi3sAu3EtSzb
"""

# ============================================================
# PAHANG POVERTY & MEDIAN INCOME NOWCASTING
# ============================================================
#
# ALTERNATIVE / SENSITIVITY FRAMEWORK
#
# PURPOSE:
# Test what happens when BOTH:
#
#   1. Actual HIES outcomes
#   2. PCHIP-completed historical outcomes
#
# are used together for model training and validation.
#
# HISTORICAL OUTCOME YEARS:
#
# 2019  = ACTUAL HIES
# 2020  = PCHIP
# 2021  = PCHIP
# 2022  = ACTUAL HIES
# 2023  = PCHIP
# 2024  = ACTUAL HIES
#
# Therefore:
#
# MODELING YEARS = 2019–2024 (6 years)
#
# FUTURE NOWCAST:
#
# 2025
# 2026
# 2027
#
# FINAL MODELS:
#
# Poverty       -> Ridge
# Median Income -> Regression Tree
#
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import os
import glob
import warnings

import numpy as np
import pandas as pd

from scipy.interpolate import PchipInterpolator

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

warnings.filterwarnings("ignore")


# ============================================================
# 2. SETTINGS
# ============================================================

INPUT_FILE = "master_panel_2019_2024_rows (1).csv"

OUTPUT_FOLDER = "FINAL_PCHIP_AUGMENTED_RIDGE_TREE_NOWCAST"

os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)

# ------------------------------------------------------------
# HIES YEARS
# ------------------------------------------------------------

HIES_YEARS = [
    2019,
    2022,
    2024
]

# ------------------------------------------------------------
# PCHIP YEARS
# ------------------------------------------------------------

INTERPOLATION_YEARS = [
    2020,
    2021,
    2023
]

# ------------------------------------------------------------
# ALL HISTORICAL MODELING YEARS
# ------------------------------------------------------------

MODEL_YEARS = [
    2019,
    2020,
    2021,
    2022,
    2023,
    2024
]

# ------------------------------------------------------------
# FUTURE YEARS
# ------------------------------------------------------------

FUTURE_YEARS = [
    2025,
    2026,
    2027
]

# ------------------------------------------------------------
# COMPLETE PERIOD
# ------------------------------------------------------------

ALL_YEARS = list(
    range(
        2019,
        2028
    )
)

# ------------------------------------------------------------
# Bootstrap
# ------------------------------------------------------------

N_BOOTSTRAP = 5000

# ------------------------------------------------------------
# Monte Carlo
# ------------------------------------------------------------

N_MONTE_CARLO = 5000

# ------------------------------------------------------------
# Random seed
# ------------------------------------------------------------

RANDOM_SEED = 42


# ============================================================
# 3. COLUMN DEFINITIONS
# ============================================================

DISTRICT_COL = "district"
YEAR_COL = "year"

# ------------------------------------------------------------
# OUTCOMES
# ------------------------------------------------------------

POVERTY_OUTCOME = "poverty_absolute_pct"

INCOME_OUTCOME = "income_median_rm"

# ------------------------------------------------------------
# SCHOOL ENROLMENT
# ------------------------------------------------------------

STUDENTS_TOTAL_COL = "students_total"

STUDENT_AGE_POP_COL = (
    "student_age_population_5_19_000"
)

# ------------------------------------------------------------
# DEPENDENCY RATIO
# ------------------------------------------------------------

WORKING_AGE_COL = (
    "working_age_population_000"
)

NONWORKING_AGE_COL = (
    "nonworking_age_population_000"
)


# ============================================================
# 4. FINAL PREDICTORS
# ============================================================
#
# These are the predictors from the latest model-selection
# experiment.
#
# POVERTY:
#
# participation_rate_pct
# school_enrolment_pct
#
# INCOME:
#
# participation_rate_pct
# unemployment_rate_pct
# dependency_ratio_pct
#
# ============================================================

POVERTY_PREDICTORS = [
    "participation_rate_pct",
    "school_enrolment_pct"
]

INCOME_PREDICTORS = [
    "participation_rate_pct",
    "unemployment_rate_pct",
    "dependency_ratio_pct"
]


# ============================================================
# 5. LOAD DATA
# ============================================================

print("\n" + "=" * 80)
print("STEP 1 — DATA LOADING")
print("=" * 80)

if os.path.exists(INPUT_FILE):

    DATA_PATH = INPUT_FILE

else:

    possible_files = glob.glob("*.csv")

    matching_files = [
        f
        for f in possible_files
        if "master_panel" in
        os.path.basename(f).lower()
    ]

    if len(matching_files) == 0:

        raise FileNotFoundError(
            "\nDataset not found.\n\n"
            "Expected filename:\n"
            f"{INPUT_FILE}\n\n"
            "Please upload the CSV and run again."
        )

    DATA_PATH = matching_files[0]


print(
    "Dataset used:",
    DATA_PATH
)

df = pd.read_csv(
    DATA_PATH
)

print(
    "Dataset shape:",
    df.shape
)


# ============================================================
# 6. BASIC CLEANING
# ============================================================

print("\n" + "=" * 80)
print("STEP 2 — BASIC CLEANING")
print("=" * 80)

df[DISTRICT_COL] = (
    df[DISTRICT_COL]
    .astype(str)
    .str.strip()
    .str.upper()
)

df[YEAR_COL] = pd.to_numeric(
    df[YEAR_COL],
    errors="coerce"
)

df = df.dropna(
    subset=[
        DISTRICT_COL,
        YEAR_COL
    ]
).copy()

df[YEAR_COL] = (
    df[YEAR_COL]
    .astype(int)
)

df = (
    df
    .sort_values(
        [
            DISTRICT_COL,
            YEAR_COL
        ]
    )
    .reset_index(drop=True)
)

districts = sorted(
    df[DISTRICT_COL].unique()
)

print(
    "Number of districts:",
    len(districts)
)

print(
    "Districts:",
    districts
)

print(
    "Years available:",
    sorted(
        df[YEAR_COL].unique()
    )
)


# ============================================================
# 7. CHECK REQUIRED COLUMNS
# ============================================================

print("\n" + "=" * 80)
print("STEP 3 — REQUIRED COLUMN CHECK")
print("=" * 80)

required_columns = [

    DISTRICT_COL,
    YEAR_COL,

    POVERTY_OUTCOME,
    INCOME_OUTCOME,

    "participation_rate_pct",
    "unemployment_rate_pct",

    STUDENTS_TOTAL_COL,
    STUDENT_AGE_POP_COL,

    WORKING_AGE_COL,
    NONWORKING_AGE_COL

]

missing_columns = [
    col
    for col in required_columns
    if col not in df.columns
]

if missing_columns:

    raise ValueError(
        "\nMissing required columns:\n"
        +
        "\n".join(
            f"- {x}"
            for x in missing_columns
        )
    )

print(
    "All required columns are available."
)


# ============================================================
# 8. DERIVE SCHOOL ENROLMENT
# ============================================================

print("\n" + "=" * 80)
print("STEP 4 — DERIVE SCHOOL ENROLMENT RATE")
print("=" * 80)

df["school_enrolment_pct"] = np.where(

    (
        df[STUDENTS_TOTAL_COL].notna()
        &
        df[STUDENT_AGE_POP_COL].notna()
        &
        (df[STUDENT_AGE_POP_COL] != 0)
    ),

    (
        df[STUDENTS_TOTAL_COL]
        /
        (
            df[STUDENT_AGE_POP_COL]
            * 1000
        )
    )
    * 100,

    np.nan
)

print(
    df[
        [
            DISTRICT_COL,
            YEAR_COL,
            STUDENTS_TOTAL_COL,
            STUDENT_AGE_POP_COL,
            "school_enrolment_pct"
        ]
    ].head(10)
)


# ============================================================
# 9. DERIVE DEPENDENCY RATIO
# ============================================================

print("\n" + "=" * 80)
print("STEP 5 — DERIVE DEPENDENCY RATIO")
print("=" * 80)

df["dependency_ratio_pct"] = np.where(

    (
        df[WORKING_AGE_COL].notna()
        &
        df[NONWORKING_AGE_COL].notna()
        &
        (df[WORKING_AGE_COL] != 0)
    ),

    (
        df[NONWORKING_AGE_COL]
        /
        df[WORKING_AGE_COL]
    )
    * 100,

    np.nan
)

print(
    df[
        [
            DISTRICT_COL,
            YEAR_COL,
            WORKING_AGE_COL,
            NONWORKING_AGE_COL,
            "dependency_ratio_pct"
        ]
    ].head(10)
)


# ============================================================
# 10. CREATE ACTUAL HIES OUTCOME COLUMNS
# ============================================================

print("\n" + "=" * 80)
print("STEP 6 — CREATE ACTUAL HIES OUTCOMES")
print("=" * 80)

df["poverty_actual_HIES"] = np.where(

    df[YEAR_COL].isin(HIES_YEARS),

    df[POVERTY_OUTCOME],

    np.nan
)

df["income_actual_HIES"] = np.where(

    df[YEAR_COL].isin(HIES_YEARS),

    df[INCOME_OUTCOME],

    np.nan
)


# ============================================================
# 11. PCHIP FUNCTION
# ============================================================

def pchip_complete_district(
    district_df,
    outcome_column
):

    observed = (
        district_df[
            district_df[YEAR_COL]
            .isin(HIES_YEARS)
        ]
        [
            [
                YEAR_COL,
                outcome_column
            ]
        ]
        .dropna()
        .sort_values(YEAR_COL)
    )

    if len(observed) < 3:

        return pd.Series(
            np.nan,
            index=ALL_YEARS,
            dtype=float
        )

    x = (
        observed[YEAR_COL]
        .astype(float)
        .values
    )

    y = (
        observed[outcome_column]
        .astype(float)
        .values
    )

    pchip = PchipInterpolator(
        x,
        y
    )

    result = {}

    for year in ALL_YEARS:

        if year in HIES_YEARS:

            idx = list(x).index(
                float(year)
            )

            result[year] = y[idx]

        elif year in INTERPOLATION_YEARS:

            result[year] = float(
                pchip(year)
            )

        else:

            result[year] = np.nan

    return pd.Series(result)


# ============================================================
# 12. APPLY PCHIP
# ============================================================

print("\n" + "=" * 80)
print("STEP 7 — PCHIP HISTORICAL COMPLETION")
print("=" * 80)

pchip_records = []

for district in districts:

    district_df = df[
        df[DISTRICT_COL] == district
    ].copy()

    poverty_series = (
        pchip_complete_district(
            district_df,
            "poverty_actual_HIES"
        )
    )

    income_series = (
        pchip_complete_district(
            district_df,
            "income_actual_HIES"
        )
    )

    for year in ALL_YEARS:

        pchip_records.append({

            DISTRICT_COL:
                district,

            YEAR_COL:
                year,

            "poverty_pchip":
                poverty_series.loc[year],

            "income_pchip":
                income_series.loc[year]

        })

pchip_df = pd.DataFrame(
    pchip_records
)


# ============================================================
# 13. MERGE PCHIP WITH ORIGINAL DATA
# ============================================================

completed = pchip_df.merge(

    df[
        [
            DISTRICT_COL,
            YEAR_COL,

            "poverty_actual_HIES",
            "income_actual_HIES",

            "participation_rate_pct",
            "unemployment_rate_pct",

            "school_enrolment_pct",
            "dependency_ratio_pct",

            "population_000",
            WORKING_AGE_COL,
            NONWORKING_AGE_COL

        ]
    ],

    on=[
        DISTRICT_COL,
        YEAR_COL
    ],

    how="left"
)


# ============================================================
# 14. CREATE COMPLETED HISTORICAL OUTCOMES
# ============================================================

completed["poverty_completed"] = np.where(

    completed[
        "poverty_actual_HIES"
    ].notna(),

    completed[
        "poverty_actual_HIES"
    ],

    np.where(

        completed[YEAR_COL]
        .isin(INTERPOLATION_YEARS),

        completed[
            "poverty_pchip"
        ],

        np.nan
    )
)


completed["income_completed"] = np.where(

    completed[
        "income_actual_HIES"
    ].notna(),

    completed[
        "income_actual_HIES"
    ],

    np.where(

        completed[YEAR_COL]
        .isin(INTERPOLATION_YEARS),

        completed[
            "income_pchip"
        ],

        np.nan
    )
)


# ============================================================
# 15. DATA TYPE
# ============================================================

completed["data_type"] = np.select(

    [

        completed[YEAR_COL]
        .isin(HIES_YEARS),

        completed[YEAR_COL]
        .isin(INTERPOLATION_YEARS)

    ],

    [

        "HIES",
        "PCHIP"

    ],

    default="FUTURE"
)


# ============================================================
# 16. SAVE PCHIP DATA
# ============================================================

completed.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "01_PCHIP_augmented_historical.csv"
    ),

    index=False
)


# ============================================================
# 17. IMPORTANT:
# BUILD SIX-YEAR MODELING DATA
# ============================================================
#
# DIFFERENCE FROM PREVIOUS VERSION:
#
# Previously:
#
#   model_data = actual HIES only
#
# NOW:
#
#   model_data = 2019–2024
#
# This means:
#
#   HIES + PCHIP
#
# ============================================================

print("\n" + "=" * 80)
print("STEP 8 — SIX-YEAR PCHIP-AUGMENTED MODEL DATA")
print("=" * 80)

model_data = completed[
    completed[YEAR_COL]
    .isin(MODEL_YEARS)
].copy()


print(
    "\nModel years:",
    sorted(
        model_data[YEAR_COL].unique()
    )
)

print(
    "\nObservations by year:"
)

print(
    model_data[
        YEAR_COL
    ]
    .value_counts()
    .sort_index()
)


print(
    "\nData type by year:"
)

print(
    model_data[
        [
            YEAR_COL,
            "data_type"
        ]
    ]
    .drop_duplicates()
    .sort_values(YEAR_COL)
)


# ============================================================
# 18. MODEL DEFINITIONS
# ============================================================

def create_models():

    models = {

        "OLS": Pipeline(
            [
                (
                    "scaler",
                    StandardScaler()
                ),
                (
                    "model",
                    LinearRegression()
                )
            ]
        ),

        "Ridge": Pipeline(
            [
                (
                    "scaler",
                    StandardScaler()
                ),
                (
                    "model",
                    Ridge(
                        alpha=10.0
                    )
                )
            ]
        ),

        "Regression Tree":
            DecisionTreeRegressor(
                max_depth=3,
                min_samples_leaf=3,
                random_state=RANDOM_SEED
            ),

        "Decision Tree":
            DecisionTreeRegressor(
                max_depth=None,
                min_samples_leaf=2,
                random_state=RANDOM_SEED
            )

    }

    return models


# ============================================================
# 19. METRICS
# ============================================================

def calculate_metrics(
    y_true,
    y_pred
):

    mae = mean_absolute_error(
        y_true,
        y_pred
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_true,
            y_pred
        )
    )

    # MAPE
    nonzero = (
        np.asarray(y_true) != 0
    )

    if nonzero.sum() > 0:

        mape = np.mean(
            np.abs(
                (
                    np.asarray(y_true)[nonzero]
                    -
                    np.asarray(y_pred)[nonzero]
                )
                /
                np.asarray(y_true)[nonzero]
            )
        ) * 100

    else:

        mape = np.nan

    # R²
    if len(y_true) >= 2:

        r2 = r2_score(
            y_true,
            y_pred
        )

    else:

        r2 = np.nan

    return (
        mae,
        rmse,
        mape,
        r2
    )


# ============================================================
# 20. POOLED LOOCV
# ============================================================
#
# IMPORTANT:
#
# Since we now have 6 years:
#
# 11 districts × 2 observations per district
# is no longer the previous setup.
#
# We use leave-one-observation-out:
#
# Each individual district-year observation is removed.
#
# Total expected observations:
#
# 11 districts × 6 years = 66
#
# assuming complete data.
#
# ============================================================

def pooled_loocv(
    data,
    outcome,
    predictors,
    model_name
):

    clean = data.dropna(
        subset=[
            outcome
        ] + predictors
    ).copy()

    clean = clean.reset_index(
        drop=True
    )

    predictions = []

    actuals = []

    prediction_records = []

    for i in range(
        len(clean)
    ):

        train = clean.drop(
            index=i
        )

        test = clean.iloc[
            [i]
        ]

        if len(train) < 5:
            continue

        model = create_models()[
            model_name
        ]

        model.fit(

            train[
                predictors
            ],

            train[
                outcome
            ]

        )

        pred = model.predict(

            test[
                predictors
            ]

        )[0]

        actual = test[
            outcome
        ].iloc[0]

        predictions.append(
            pred
        )

        actuals.append(
            actual
        )

        prediction_records.append({

            DISTRICT_COL:
                test[
                    DISTRICT_COL
                ].iloc[0],

            YEAR_COL:
                test[
                    YEAR_COL
                ].iloc[0],

            "data_type":
                test[
                    "data_type"
                ].iloc[0],

            "actual":
                actual,

            "predicted":
                pred,

            "error":
                actual - pred,

            "absolute_error":
                abs(
                    actual - pred
                )

        })

    y_true = np.array(
        actuals
    )

    y_pred = np.array(
        predictions
    )

    mae, rmse, mape, r2 = (
        calculate_metrics(
            y_true,
            y_pred
        )
    )

    prediction_df = pd.DataFrame(
        prediction_records
    )

    return {

        "model":
            model_name,

        "observations":
            len(y_true),

        "MAE":
            mae,

        "RMSE":
            rmse,

        "MAPE":
            mape,

        "R2":
            r2,

        "predictions":
            prediction_df

    }


# ============================================================
# 21. TEST ALL MODELS — POVERTY
# ============================================================

print("\n" + "=" * 80)
print("STEP 9 — POOLED LOOCV: POVERTY")
print("=" * 80)

poverty_models_results = []

poverty_prediction_storage = {}

for model_name in [

    "OLS",
    "Ridge",
    "Regression Tree",
    "Decision Tree"

]:

    print(
        f"Testing poverty model: "
        f"{model_name}"
    )

    result = pooled_loocv(

        model_data,

        "poverty_completed",

        POVERTY_PREDICTORS,

        model_name

    )

    poverty_models_results.append({

        "Model":
            model_name,

        "Observations":
            result["observations"],

        "LOOCV MAE":
            result["MAE"],

        "LOOCV RMSE":
            result["RMSE"],

        "LOOCV MAPE":
            result["MAPE"],

        "LOOCV R2":
            result["R2"]

    })

    poverty_prediction_storage[
        model_name
    ] = result["predictions"]


poverty_model_comparison = pd.DataFrame(
    poverty_models_results
)


print(
    "\nPOVERTY MODEL COMPARISON:"
)

print(
    poverty_model_comparison.to_string(
        index=False
    )
)


# ============================================================
# 22. TEST ALL MODELS — INCOME
# ============================================================

print("\n" + "=" * 80)
print("STEP 10 — POOLED LOOCV: MEDIAN INCOME")
print("=" * 80)

income_models_results = []

income_prediction_storage = {}

for model_name in [

    "OLS",
    "Ridge",
    "Regression Tree",
    "Decision Tree"

]:

    print(
        f"Testing income model: "
        f"{model_name}"
    )

    result = pooled_loocv(

        model_data,

        "income_completed",

        INCOME_PREDICTORS,

        model_name

    )

    income_models_results.append({

        "Model":
            model_name,

        "Observations":
            result["observations"],

        "LOOCV MAE":
            result["MAE"],

        "LOOCV RMSE":
            result["RMSE"],

        "LOOCV MAPE":
            result["MAPE"],

        "LOOCV R2":
            result["R2"]

    })

    income_prediction_storage[
        model_name
    ] = result["predictions"]


income_model_comparison = pd.DataFrame(
    income_models_results
)


print(
    "\nMEDIAN INCOME MODEL COMPARISON:"
)

print(
    income_model_comparison.to_string(
        index=False
    )
)


# ============================================================
# 23. SELECT FINAL MODELS
# ============================================================
#
# Based on your previous experiment:
#
# Poverty       = Ridge
# Median Income = Regression Tree
#
# We keep these as the FINAL models for this experiment.
# ============================================================

BEST_POVERTY_MODEL = "Ridge"

BEST_INCOME_MODEL = "Regression Tree"


print("\n" + "=" * 80)
print("STEP 11 — FINAL MODEL SELECTION")
print("=" * 80)

print(
    "BEST POVERTY MODEL:",
    BEST_POVERTY_MODEL
)

print(
    "Poverty predictors:",
    ", ".join(
        POVERTY_PREDICTORS
    )
)

print()

print(
    "BEST MEDIAN INCOME MODEL:",
    BEST_INCOME_MODEL
)

print(
    "Income predictors:",
    ", ".join(
        INCOME_PREDICTORS
    )
)


# ============================================================
# 24. FINAL SIX-YEAR TRAINING DATA
# ============================================================

poverty_train = model_data.dropna(
    subset=[
        "poverty_completed"
    ] + POVERTY_PREDICTORS
).copy()


income_train = model_data.dropna(
    subset=[
        "income_completed"
    ] + INCOME_PREDICTORS
).copy()


print("\n" + "=" * 80)
print("STEP 12 — FINAL TRAINING SAMPLE")
print("=" * 80)

print(
    "Poverty observations:",
    len(poverty_train)
)

print(
    "Income observations:",
    len(income_train)
)


# ============================================================
# 25. FIT FINAL POVERTY MODEL
# ============================================================

poverty_model = create_models()[
    BEST_POVERTY_MODEL
]

poverty_model.fit(

    poverty_train[
        POVERTY_PREDICTORS
    ],

    poverty_train[
        "poverty_completed"
    ]

)


# ============================================================
# 26. FIT FINAL INCOME MODEL
# ============================================================

income_model = create_models()[
    BEST_INCOME_MODEL
]

income_model.fit(

    income_train[
        INCOME_PREDICTORS
    ],

    income_train[
        "income_completed"
    ]

)


# ============================================================
# 27. FUTURE PREDICTOR PROJECTION
# ============================================================

print("\n" + "=" * 80)
print("STEP 13 — FUTURE PREDICTOR PROJECTION")
print("=" * 80)


def project_predictor(
    district_df,
    predictor,
    future_years
):

    temp = district_df[
        [
            YEAR_COL,
            predictor
        ]
    ].dropna().copy()

    temp = temp.sort_values(
        YEAR_COL
    )

    if len(temp) == 0:

        return {
            year: np.nan
            for year in future_years
        }

    if len(temp) == 1:

        value = float(
            temp[predictor].iloc[0]
        )

        return {
            year: value
            for year in future_years
        }

    x = temp[
        YEAR_COL
    ].values.astype(float)

    y = temp[
        predictor
    ].values.astype(float)

    trend = LinearRegression()

    trend.fit(
        x.reshape(-1, 1),
        y
    )

    predictions = trend.predict(
        np.array(
            future_years
        ).reshape(-1, 1)
    )

    return {

        year: value

        for year, value in zip(
            future_years,
            predictions
        )

    }


all_predictors = sorted(
    set(
        POVERTY_PREDICTORS
        +
        INCOME_PREDICTORS
    )
)


future_records = []

for district in districts:

    district_df = df[
        df[DISTRICT_COL] == district
    ].copy()

    forecasts = {}

    for predictor in all_predictors:

        forecasts[
            predictor
        ] = project_predictor(

            district_df,

            predictor,

            FUTURE_YEARS

        )

    for year in FUTURE_YEARS:

        row = {

            DISTRICT_COL:
                district,

            YEAR_COL:
                year

        }

        for predictor in all_predictors:

            row[predictor] = (
                forecasts[
                    predictor
                ][year]
            )

        future_records.append(
            row
        )


future_predictors = pd.DataFrame(
    future_records
)


# ============================================================
# 28. FUTURE PREDICTOR NULL HANDLING
# ============================================================

for predictor in all_predictors:

    for year in FUTURE_YEARS:

        mask = (
            future_predictors[
                YEAR_COL
            ]
            ==
            year
        )

        median_value = (
            future_predictors
            .loc[
                mask,
                predictor
            ]
            .median()
        )

        future_predictors.loc[
            mask,
            predictor
        ] = (
            future_predictors
            .loc[
                mask,
                predictor
            ]
            .fillna(
                median_value
            )
        )


# ============================================================
# 29. SAVE FUTURE PREDICTORS
# ============================================================

future_predictors.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "02_future_predictors_2025_2027.csv"
    ),

    index=False

)


# ============================================================
# 30. FUTURE POINT NOWCAST
# ============================================================

poverty_future_point = (
    poverty_model.predict(
        future_predictors[
            POVERTY_PREDICTORS
        ]
    )
)


income_future_point = (
    income_model.predict(
        future_predictors[
            INCOME_PREDICTORS
        ]
    )
)


# ============================================================
# 31. DISTRICT CLUSTER BOOTSTRAP
# ============================================================

print("\n" + "=" * 80)
print("STEP 14 — DISTRICT CLUSTER BOOTSTRAP")
print("=" * 80)


def clustered_bootstrap_predictions(
    data,
    outcome,
    predictors,
    model_name,
    future_data,
    n_bootstrap=5000,
    random_seed=42
):

    rng = np.random.default_rng(
        random_seed
    )

    available_districts = (
        data[DISTRICT_COL]
        .dropna()
        .unique()
        .tolist()
    )

    n_districts = len(
        available_districts
    )

    predictions = []

    for b in range(
        n_bootstrap
    ):

        sampled_districts = rng.choice(

            available_districts,

            size=n_districts,

            replace=True

        )

        bootstrap_parts = []

        for district in sampled_districts:

            district_data = data[
                data[DISTRICT_COL]
                ==
                district
            ]

            bootstrap_parts.append(
                district_data
            )

        bootstrap_data = pd.concat(
            bootstrap_parts,
            ignore_index=True
        )

        bootstrap_data = bootstrap_data.dropna(
            subset=[
                outcome
            ] + predictors
        )

        if len(bootstrap_data) < 5:
            continue

        model = create_models()[
            model_name
        ]

        try:

            model.fit(

                bootstrap_data[
                    predictors
                ],

                bootstrap_data[
                    outcome
                ]

            )

            pred = model.predict(
                future_data[
                    predictors
                ]
            )

            predictions.append(
                pred
            )

        except Exception:
            continue

    if len(predictions) == 0:

        raise ValueError(
            "No valid bootstrap predictions."
        )

    return np.vstack(
        predictions
    )


# ============================================================
# 32. POVERTY BOOTSTRAP
# ============================================================

poverty_bootstrap = (
    clustered_bootstrap_predictions(

        poverty_train,

        "poverty_completed",

        POVERTY_PREDICTORS,

        BEST_POVERTY_MODEL,

        future_predictors[
            POVERTY_PREDICTORS
        ],

        n_bootstrap=N_BOOTSTRAP,

        random_seed=RANDOM_SEED

    )
)


# ============================================================
# 33. INCOME BOOTSTRAP
# ============================================================

income_bootstrap = (
    clustered_bootstrap_predictions(

        income_train,

        "income_completed",

        INCOME_PREDICTORS,

        BEST_INCOME_MODEL,

        future_predictors[
            INCOME_PREDICTORS
        ],

        n_bootstrap=N_BOOTSTRAP,

        random_seed=RANDOM_SEED + 100

    )
)


print(
    "Poverty bootstrap draws:",
    len(poverty_bootstrap)
)

print(
    "Income bootstrap draws:",
    len(income_bootstrap)
)


# ============================================================
# 34. MONTE CARLO PREDICTOR UNCERTAINTY
# ============================================================

def monte_carlo_predictor_uncertainty(

    historical_df,
    future_df,
    predictors,
    n_simulations=5000,
    random_seed=42

):

    rng = np.random.default_rng(
        random_seed
    )

    predictor_sd = {}

    for predictor in predictors:

        values = (
            historical_df[
                predictor
            ]
            .dropna()
        )

        if len(values) >= 2:

            predictor_sd[
                predictor
            ] = float(
                values.std()
            )

        else:

            predictor_sd[
                predictor
            ] = 0.0

    simulations = []

    base_X = future_df[
        predictors
    ].copy()

    for _ in range(
        n_simulations
    ):

        simulated_X = base_X.copy()

        for predictor in predictors:

            sd = predictor_sd[
                predictor
            ]

            if sd > 0:

                noise = rng.normal(

                    0,

                    sd * 0.05,

                    size=len(
                        simulated_X
                    )

                )

                simulated_X[
                    predictor
                ] = (
                    simulated_X[
                        predictor
                    ]
                    +
                    noise
                )

        simulations.append(
            simulated_X
        )

    return simulations


# ============================================================
# 35. POVERTY MONTE CARLO
# ============================================================

poverty_mc_X = (
    monte_carlo_predictor_uncertainty(

        poverty_train,

        future_predictors,

        POVERTY_PREDICTORS,

        n_simulations=N_MONTE_CARLO,

        random_seed=RANDOM_SEED

    )
)


poverty_mc_predictions = []

for X_sim in poverty_mc_X:

    poverty_mc_predictions.append(

        poverty_model.predict(

            X_sim[
                POVERTY_PREDICTORS
            ]

        )

    )


poverty_mc_predictions = np.vstack(
    poverty_mc_predictions
)


# ============================================================
# 36. INCOME MONTE CARLO
# ============================================================

income_mc_X = (
    monte_carlo_predictor_uncertainty(

        income_train,

        future_predictors,

        INCOME_PREDICTORS,

        n_simulations=N_MONTE_CARLO,

        random_seed=RANDOM_SEED + 100

    )
)


income_mc_predictions = []

for X_sim in income_mc_X:

    income_mc_predictions.append(

        income_model.predict(

            X_sim[
                INCOME_PREDICTORS
            ]

        )

    )


income_mc_predictions = np.vstack(
    income_mc_predictions
)


# ============================================================
# 37. COMBINE BOOTSTRAP + MONTE CARLO
# ============================================================

def combine_uncertainty(

    bootstrap_predictions,
    mc_predictions,
    n_draws=5000,
    random_seed=42

):

    rng = np.random.default_rng(
        random_seed
    )

    n_boot = len(
        bootstrap_predictions
    )

    n_mc = len(
        mc_predictions
    )

    boot_idx = rng.integers(

        0,
        n_boot,
        size=n_draws

    )

    mc_idx = rng.integers(

        0,
        n_mc,
        size=n_draws

    )

    combined = (

        bootstrap_predictions[
            boot_idx
        ]

        +

        (
            mc_predictions[
                mc_idx
            ]

            -

            mc_predictions.mean(
                axis=0
            )
        )

    )

    return combined


poverty_combined_sim = (
    combine_uncertainty(

        poverty_bootstrap,

        poverty_mc_predictions,

        n_draws=N_MONTE_CARLO,

        random_seed=RANDOM_SEED

    )
)


income_combined_sim = (
    combine_uncertainty(

        income_bootstrap,

        income_mc_predictions,

        n_draws=N_MONTE_CARLO,

        random_seed=RANDOM_SEED + 100

    )
)


# ============================================================
# 38. FUTURE 95% INTERVALS
# ============================================================

poverty_lower = np.percentile(

    poverty_combined_sim,

    2.5,

    axis=0

)

poverty_upper = np.percentile(

    poverty_combined_sim,

    97.5,

    axis=0

)


income_lower = np.percentile(

    income_combined_sim,

    2.5,

    axis=0

)

income_upper = np.percentile(

    income_combined_sim,

    97.5,

    axis=0

)


# ============================================================
# 39. FUTURE NOWCAST TABLE
# ============================================================

future_nowcast = future_predictors[
    [
        DISTRICT_COL,
        YEAR_COL
    ]
].copy()


future_nowcast[
    "poverty_nowcast"
] = poverty_future_point


future_nowcast[
    "poverty_lower"
] = poverty_lower


future_nowcast[
    "poverty_upper"
] = poverty_upper


future_nowcast[
    "income_nowcast"
] = income_future_point


future_nowcast[
    "income_lower"
] = income_lower


future_nowcast[
    "income_upper"
] = income_upper


future_nowcast[
    "poverty_data_type"
] = (
    "Nowcast - "
    + BEST_POVERTY_MODEL
)


future_nowcast[
    "income_data_type"
] = (
    "Nowcast - "
    + BEST_INCOME_MODEL
)


# ============================================================
# 40. SAVE FUTURE NOWCAST
# ============================================================

future_nowcast.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "03_future_nowcast_2025_2027.csv"
    ),

    index=False

)


# ============================================================
# 41. CREATE FINAL MASTER PANEL
# ============================================================

print("\n" + "=" * 80)
print("STEP 15 — BUILD FINAL MASTER PANEL")
print("=" * 80)

master = pd.MultiIndex.from_product(

    [
        districts,
        ALL_YEARS
    ],

    names=[
        DISTRICT_COL,
        YEAR_COL
    ]

).to_frame(
    index=False
)


# ============================================================
# 42. MERGE ORIGINAL VARIABLES
# ============================================================

original_variables = df[
    [
        DISTRICT_COL,
        YEAR_COL,

        "poverty_actual_HIES",
        "income_actual_HIES",

        "participation_rate_pct",
        "unemployment_rate_pct",
        "school_enrolment_pct",
        "dependency_ratio_pct",

        "population_000",
        WORKING_AGE_COL,
        NONWORKING_AGE_COL

    ]
].copy()


master = master.merge(

    original_variables,

    on=[
        DISTRICT_COL,
        YEAR_COL
    ],

    how="left"

)


# ============================================================
# 43. MERGE PCHIP
# ============================================================

master = master.merge(

    pchip_df,

    on=[
        DISTRICT_COL,
        YEAR_COL
    ],

    how="left"

)


# ============================================================
# 44. CREATE OUTPUT COLUMNS
# ============================================================

for col in [

    "poverty_nowcast",
    "poverty_lower",
    "poverty_upper",

    "income_nowcast",
    "income_lower",
    "income_upper"

]:

    master[col] = np.nan


# ============================================================
# 45. ACTUAL HIES
# ============================================================

hies_mask = (
    master[YEAR_COL]
    .isin(HIES_YEARS)
)


master.loc[
    hies_mask,
    "poverty_nowcast"
] = master.loc[
    hies_mask,
    "poverty_actual_HIES"
]


master.loc[
    hies_mask,
    "income_nowcast"
] = master.loc[
    hies_mask,
    "income_actual_HIES"
]


master.loc[
    hies_mask,
    "poverty_lower"
] = master.loc[
    hies_mask,
    "poverty_actual_HIES"
]


master.loc[
    hies_mask,
    "poverty_upper"
] = master.loc[
    hies_mask,
    "poverty_actual_HIES"
]


master.loc[
    hies_mask,
    "income_lower"
] = master.loc[
    hies_mask,
    "income_actual_HIES"
]


master.loc[
    hies_mask,
    "income_upper"
] = master.loc[
    hies_mask,
    "income_actual_HIES"
]


# ============================================================
# 46. PCHIP YEARS
# ============================================================

pchip_mask = (
    master[YEAR_COL]
    .isin(INTERPOLATION_YEARS)
)


master.loc[
    pchip_mask,
    "poverty_nowcast"
] = master.loc[
    pchip_mask,
    "poverty_pchip"
]


master.loc[
    pchip_mask,
    "income_nowcast"
] = master.loc[
    pchip_mask,
    "income_pchip"
]


master.loc[
    pchip_mask,
    "poverty_lower"
] = master.loc[
    pchip_mask,
    "poverty_pchip"
]


master.loc[
    pchip_mask,
    "poverty_upper"
] = master.loc[
    pchip_mask,
    "poverty_pchip"
]


master.loc[
    pchip_mask,
    "income_lower"
] = master.loc[
    pchip_mask,
    "income_pchip"
]


master.loc[
    pchip_mask,
    "income_upper"
] = master.loc[
    pchip_mask,
    "income_pchip"
]


# ============================================================
# 47. FUTURE NOWCAST
# ============================================================

master = master.merge(

    future_nowcast[
        [
            DISTRICT_COL,
            YEAR_COL,

            "poverty_nowcast",
            "poverty_lower",
            "poverty_upper",

            "income_nowcast",
            "income_lower",
            "income_upper"

        ]
    ],

    on=[
        DISTRICT_COL,
        YEAR_COL
    ],

    how="left",

    suffixes=(
        "",
        "_future"
    )

)


future_mask = (
    master[YEAR_COL]
    .isin(FUTURE_YEARS)
)


for col in [

    "poverty_nowcast",
    "poverty_lower",
    "poverty_upper",

    "income_nowcast",
    "income_lower",
    "income_upper"

]:

    master.loc[
        future_mask,
        col
    ] = master.loc[
        future_mask,
        col + "_future"
    ]


# ============================================================
# 48. DATA TYPE
# ============================================================

master["poverty_data_type"] = np.select(

    [

        master[YEAR_COL]
        .isin(HIES_YEARS),

        master[YEAR_COL]
        .isin(INTERPOLATION_YEARS),

        master[YEAR_COL]
        .isin(FUTURE_YEARS)

    ],

    [

        "HIES",

        "PCHIP",

        "Nowcast - "
        + BEST_POVERTY_MODEL

    ],

    default="Unknown"
)


master["income_data_type"] = np.select(

    [

        master[YEAR_COL]
        .isin(HIES_YEARS),

        master[YEAR_COL]
        .isin(INTERPOLATION_YEARS),

        master[YEAR_COL]
        .isin(FUTURE_YEARS)

    ],

    [

        "HIES",

        "PCHIP",

        "Nowcast - "
        + BEST_INCOME_MODEL

    ],

    default="Unknown"
)


# ============================================================
# 49. COMBINED OUTCOMES
# ============================================================

master[
    "poverty_combined"
] = master[
    "poverty_actual_HIES"
].combine_first(
    master[
        "poverty_nowcast"
    ]
)


master[
    "income_combined"
] = master[
    "income_actual_HIES"
].combine_first(
    master[
        "income_nowcast"
    ]
)


# ============================================================
# 50. FINAL TABLE
# ============================================================

final_table = master[
    [

        DISTRICT_COL,
        YEAR_COL,

        "poverty_nowcast",
        "poverty_actual_HIES",
        "poverty_combined",
        "poverty_data_type",
        "poverty_lower",
        "poverty_upper",

        "income_nowcast",
        "income_actual_HIES",
        "income_combined",
        "income_data_type",
        "income_lower",
        "income_upper"

    ]
].copy()


# ============================================================
# 51. ROUND
# ============================================================

numeric_columns = [

    "poverty_nowcast",
    "poverty_actual_HIES",
    "poverty_combined",
    "poverty_lower",
    "poverty_upper",

    "income_nowcast",
    "income_actual_HIES",
    "income_combined",
    "income_lower",
    "income_upper"

]

for col in numeric_columns:

    final_table[col] = (
        pd.to_numeric(
            final_table[col],
            errors="coerce"
        )
        .round(2)
    )


# ============================================================
# 52. FINAL VALIDATION METRIC TABLE
# ============================================================

poverty_final_result = pooled_loocv(

    model_data,

    "poverty_completed",

    POVERTY_PREDICTORS,

    BEST_POVERTY_MODEL

)


income_final_result = pooled_loocv(

    model_data,

    "income_completed",

    INCOME_PREDICTORS,

    BEST_INCOME_MODEL

)


# ============================================================
# 53. CREATE DASHBOARD-STYLE METRIC TABLE
# ============================================================

validation_summary = pd.DataFrame({

    "Metric": [

        "LOOCV MAE",
        "LOOCV RMSE",
        "Validation MAPE",
        "Validation R²"

    ],

    "Poverty": [

        poverty_final_result["MAE"],

        poverty_final_result["RMSE"],

        poverty_final_result["MAPE"],

        poverty_final_result["R2"]

    ],

    "Income": [

        income_final_result["MAE"],

        income_final_result["RMSE"],

        income_final_result["MAPE"],

        income_final_result["R2"]

    ]

})


# ============================================================
# 54. CI COVERAGE
# ============================================================
#
# NOTE:
#
# There are no genuine future confidence intervals that can
# be tested against 2025–2027 yet because those outcomes are
# not observed.
#
# Therefore we calculate CI coverage using the historical
# PCHIP-augmented LOOCV predictions only if the prediction
# itself is associated with an empirical bootstrap interval.
#
# To avoid falsely reporting a coverage statistic, we leave
# it as NaN in this experiment.
#
# ============================================================

validation_summary = pd.concat(

    [

        pd.DataFrame({

            "Metric":
                ["95% CI Coverage"],

            "Poverty":
                [np.nan],

            "Income":
                [np.nan]

        }),

        validation_summary

    ],

    ignore_index=True

)


# ============================================================
# 55. FORMAT DASHBOARD TABLE
# ============================================================

print("\n" + "=" * 80)
print("PCHIP-AUGMENTED VALIDATION METRICS")
print("=" * 80)

display_table = validation_summary.copy()

display_table.loc[
    display_table["Metric"]
    == "LOOCV MAE",
    ["Poverty", "Income"]
] = display_table.loc[
    display_table["Metric"]
    == "LOOCV MAE",
    ["Poverty", "Income"]
].round(4)


display_table.loc[
    display_table["Metric"]
    == "LOOCV RMSE",
    ["Poverty", "Income"]
] = display_table.loc[
    display_table["Metric"]
    == "LOOCV RMSE",
    ["Poverty", "Income"]
].round(4)


display_table.loc[
    display_table["Metric"]
    == "Validation MAPE",
    ["Poverty", "Income"]
] = display_table.loc[
    display_table["Metric"]
    == "Validation MAPE",
    ["Poverty", "Income"]
].round(4)


display_table.loc[
    display_table["Metric"]
    == "Validation R²",
    ["Poverty", "Income"]
] = display_table.loc[
    display_table["Metric"]
    == "Validation R²",
    ["Poverty", "Income"]
].round(4)


print(
    display_table.to_string(
        index=False
    )
)


# ============================================================
# 56. SAVE MODEL COMPARISON
# ============================================================

poverty_model_comparison.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "04_poverty_model_comparison.csv"
    ),

    index=False

)


income_model_comparison.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "05_income_model_comparison.csv"
    ),

    index=False

)


validation_summary.to_csv(

    os.path.join(
        OUTPUT_FOLDER,
        "06_validation_metrics_summary.csv"
    ),

    index=False

)


# ============================================================
# 57. SAVE FINAL CSV
# ============================================================

FINAL_CSV = os.path.join(

    OUTPUT_FOLDER,

    "FINAL_PCHIP_AUGMENTED_PAHANG_NOWCAST_2019_2027.csv"

)

final_table.to_csv(

    FINAL_CSV,

    index=False

)


# ============================================================
# 58. SAVE EXCEL
# ============================================================

FINAL_EXCEL = os.path.join(

    OUTPUT_FOLDER,

    "FINAL_PCHIP_AUGMENTED_PAHANG_NOWCAST_2019_2027.xlsx"

)


with pd.ExcelWriter(

    FINAL_EXCEL,

    engine="openpyxl"

) as writer:

    final_table.to_excel(

        writer,

        sheet_name="Final Nowcast",

        index=False

    )

    completed.to_excel(

        writer,

        sheet_name="PCHIP Historical",

        index=False

    )

    poverty_model_comparison.to_excel(

        writer,

        sheet_name="Poverty Models",

        index=False

    )

    income_model_comparison.to_excel(

        writer,

        sheet_name="Income Models",

        index=False

    )

    validation_summary.to_excel(

        writer,

        sheet_name="Validation Metrics",

        index=False

    )

    future_predictors.to_excel(

        writer,

        sheet_name="Future Predictors",

        index=False

    )

    future_nowcast.to_excel(

        writer,

        sheet_name="Future Nowcast",

        index=False

    )


# ============================================================
# 59. FINAL NULL CHECK
# ============================================================

print("\n" + "=" * 80)
print("STEP 16 — FINAL NULL CHECK")
print("=" * 80)

for col in [

    "poverty_nowcast",
    "poverty_combined",
    "poverty_data_type",

    "income_nowcast",
    "income_combined",
    "income_data_type"

]:

    print(

        f"{col:30s}"
        f" NULL = "
        f"{final_table[col].isna().sum()}"

    )


# ============================================================
# 60. INTERVAL CHECK
# ============================================================

poverty_invalid = (

    final_table[
        "poverty_lower"
    ]

    >

    final_table[
        "poverty_upper"
    ]

).sum()


income_invalid = (

    final_table[
        "income_lower"
    ]

    >

    final_table[
        "income_upper"
    ]

).sum()


print("\n" + "=" * 80)
print("STEP 17 — INTERVAL CHECK")
print("=" * 80)

print(
    "Invalid poverty intervals:",
    poverty_invalid
)

print(
    "Invalid income intervals:",
    income_invalid
)


# ============================================================
# 61. ROW CHECK
# ============================================================

expected_rows = (

    len(districts)
    *
    len(ALL_YEARS)

)

actual_rows = len(
    final_table
)


print("\n" + "=" * 80)
print("STEP 18 — ROW CHECK")
print("=" * 80)

print(
    "Expected rows:",
    expected_rows
)

print(
    "Actual rows:",
    actual_rows
)


if actual_rows != expected_rows:

    raise ValueError(
        "Final row count is incorrect."
    )


# ============================================================
# 62. FINAL MODEL RESULTS
# ============================================================

print("\n" + "=" * 80)
print("OFFICIAL PCHIP-AUGMENTED LOOCV RESULTS")
print("=" * 80)


print(
    "\nPOVERTY — RIDGE"
)

print(
    "Predictors:",
    ", ".join(
        POVERTY_PREDICTORS
    )
)

print(
    "Observations:",
    poverty_final_result[
        "observations"
    ]
)

print(
    f"LOOCV MAE: "
    f"{poverty_final_result['MAE']:.4f}"
)

print(
    f"LOOCV RMSE: "
    f"{poverty_final_result['RMSE']:.4f}"
)

print(
    f"LOOCV MAPE: "
    f"{poverty_final_result['MAPE']:.4f}%"
)

print(
    f"LOOCV R²: "
    f"{poverty_final_result['R2']:.4f}"
)


print(
    "\nMEDIAN INCOME — REGRESSION TREE"
)

print(
    "Predictors:",
    ", ".join(
        INCOME_PREDICTORS
    )
)

print(
    "Observations:",
    income_final_result[
        "observations"
    ]
)

print(
    f"LOOCV MAE: "
    f"{income_final_result['MAE']:.4f}"
)

print(
    f"LOOCV RMSE: "
    f"{income_final_result['RMSE']:.4f}"
)

print(
    f"LOOCV MAPE: "
    f"{income_final_result['MAPE']:.4f}%"
)

print(
    f"LOOCV R²: "
    f"{income_final_result['R2']:.4f}"
)


# ============================================================
# 63. FINAL DASHBOARD TABLE
# ============================================================

print("\n" + "=" * 80)
print("FINAL VALIDATION COMPARISON")
print("=" * 80)

print(
    validation_summary.to_string(
        index=False
    )
)


# ============================================================
# 64. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("FINAL SUMMARY")
print("=" * 80)

print(
    "Input dataset:",
    DATA_PATH
)

print(
    "Districts:",
    len(districts)
)

print(
    "Historical modeling years:",
    MODEL_YEARS
)

print(
    "Future nowcast years:",
    FUTURE_YEARS
)

print(
    "\nActual HIES years:",
    HIES_YEARS
)

print(
    "PCHIP years:",
    INTERPOLATION_YEARS
)

print(
    "\nPoverty model:",
    BEST_POVERTY_MODEL
)

print(
    "Poverty predictors:",
    POVERTY_PREDICTORS
)

print(
    "\nMedian income model:",
    BEST_INCOME_MODEL
)

print(
    "Income predictors:",
    INCOME_PREDICTORS
)

print(
    "\nBootstrap replications:",
    N_BOOTSTRAP
)

print(
    "Monte Carlo simulations:",
    N_MONTE_CARLO
)

print(
    "\nFINAL CSV:"
)

print(
    FINAL_CSV
)

print(
    "\nFINAL EXCEL:"
)

print(
    FINAL_EXCEL
)

print(
    "\n" + "=" * 80
)

print(
    "DONE — SIX-YEAR PCHIP-AUGMENTED "
    "NOWCAST EXPERIMENT"
)

print(
    "=" * 80
)

# ============================================================
# PAHANG STATE-LEVEL SUMMARY TABLE
# ============================================================
#
# Purpose:
# Create one overall Pahang value for each year
# from the 11 district-level estimates.
#
# Poverty:
#   - State poverty = simple mean of district poverty rates
#   - Lower / Upper = mean of district lower / upper bounds
#
# Median Income:
#   - State median income = median of district median incomes
#   - Lower / Upper = median of district lower / upper bounds
#
# This table is for dashboard-level presentation.
# ============================================================

pahang_summary = (
    final_table
    .groupby("year")
    .agg(
        poverty=(
            "poverty_combined",
            "mean"
        ),

        poverty_lower=(
            "poverty_lower",
            "mean"
        ),

        poverty_upper=(
            "poverty_upper",
            "mean"
        ),

        median_income=(
            "income_combined",
            "median"
        ),

        median_income_lower=(
            "income_lower",
            "median"
        ),

        median_income_upper=(
            "income_upper",
            "median"
        )
    )
    .reset_index()
)

# Round values
pahang_summary[
    [
        "poverty",
        "poverty_lower",
        "poverty_upper",
        "median_income",
        "median_income_lower",
        "median_income_upper"
    ]
] = pahang_summary[
    [
        "poverty",
        "poverty_lower",
        "poverty_upper",
        "median_income",
        "median_income_lower",
        "median_income_upper"
    ]
].round(2)


# ============================================================
# DISPLAY
# ============================================================

print("\n" + "=" * 80)
print("PAHANG STATE-LEVEL SUMMARY")
print("=" * 80)

print(pahang_summary.to_string(index=False))


# ============================================================
# SAVE CSV
# ============================================================

pahang_summary.to_csv(
    os.path.join(
        OUTPUT_FOLDER,
        "PAHANG_STATE_LEVEL_SUMMARY_2019_2027.csv"
    ),
    index=False
)


# ============================================================
# SAVE TO EXCEL
# ============================================================

pahang_excel = os.path.join(
    OUTPUT_FOLDER,
    "PAHANG_STATE_LEVEL_SUMMARY_2019_2027.xlsx"
)

with pd.ExcelWriter(
    pahang_excel,
    engine="openpyxl"
) as writer:

    pahang_summary.to_excel(
        writer,
        sheet_name="Pahang Summary",
        index=False
    )

print("\nSaved:")
print(
    os.path.join(
        OUTPUT_FOLDER,
        "PAHANG_STATE_LEVEL_SUMMARY_2019_2027.csv"
    )
)

print(pahang_excel)

# ============================================================
# PAHANG OVERALL STATE-LEVEL TABLE
# ============================================================
#
# Creates a simple Pahang-level summary from final_table.
#
# Output:
#   year
#   poverty_pahang
#   median_income_pahang
#
# IMPORTANT:
# Poverty:
#   population-weighted average of district poverty rates
#
# Median income:
#   population-weighted average of district median incomes
#   This is an AGGREGATED DISTRICT-MEDIAN INDICATOR,
#   not a true population median income for Pahang.
#
# ============================================================

print("\n" + "=" * 80)
print("PAHANG OVERALL STATE-LEVEL TABLE")
print("=" * 80)


# ------------------------------------------------------------
# 1. CHECK REQUIRED COLUMNS
# ------------------------------------------------------------

required_columns = [
    "district",
    "year",
    "poverty_combined",
    "income_combined"
]

missing_columns = [
    col for col in required_columns
    if col not in final_table.columns
]

if missing_columns:
    raise ValueError(
        f"Missing columns in final_table: {missing_columns}"
    )


# ------------------------------------------------------------
# 2. FIND POPULATION COLUMN
# ------------------------------------------------------------
#
# Your master dataset may contain different population
# variable names.
#
# We search for a suitable population variable.
#
# ------------------------------------------------------------

population_candidates = [
    "population_000",
    "population_total_000",
    "population_total",
    "total_population",
    "population",
    "population_000s"
]

population_col = None

for col in population_candidates:
    if col in final_table.columns:
        population_col = col
        break

if population_col is None:

    print(
        "\nWARNING:"
        "\nNo population column was found."
        "\nUsing SIMPLE district averages instead."
    )

else:

    print(
        f"\nPopulation column used: {population_col}"
    )


# ------------------------------------------------------------
# 3. CREATE PAHANG OVERALL TABLE
# ------------------------------------------------------------

pahang_rows = []


for year in sorted(final_table["year"].unique()):

    temp = final_table[
        final_table["year"] == year
    ].copy()


    # --------------------------------------------------------
    # CASE A — POPULATION AVAILABLE
    # --------------------------------------------------------

    if population_col is not None:

        temp = temp[
            temp[population_col].notna()
        ].copy()

        temp = temp[
            temp[population_col] > 0
        ].copy()


        # ----------------------------------------------------
        # Poverty
        # ----------------------------------------------------

        poverty_pahang = np.average(
            temp["poverty_combined"],
            weights=temp[population_col]
        )


        # ----------------------------------------------------
        # Median income
        # ----------------------------------------------------
        #
        # This is the population-weighted average of
        # district median incomes.
        #
        # It should NOT be interpreted as the exact
        # Pahang population median income.
        #
        # ----------------------------------------------------

        income_pahang = np.average(
            temp["income_combined"],
            weights=temp[population_col]
        )


    # --------------------------------------------------------
    # CASE B — NO POPULATION AVAILABLE
    # --------------------------------------------------------

    else:

        poverty_pahang = temp[
            "poverty_combined"
        ].mean()

        income_pahang = temp[
            "income_combined"
        ].mean()


    # --------------------------------------------------------
    # Store results
    # --------------------------------------------------------

    pahang_rows.append({
        "year": year,
        "poverty_pahang": poverty_pahang,
        "median_income_pahang": income_pahang
    })


# ------------------------------------------------------------
# 4. CREATE DATAFRAME
# ------------------------------------------------------------

pahang_overall = pd.DataFrame(
    pahang_rows
)


# ------------------------------------------------------------
# 5. ROUND VALUES
# ------------------------------------------------------------

pahang_overall["poverty_pahang"] = (
    pahang_overall["poverty_pahang"]
    .round(2)
)

pahang_overall["median_income_pahang"] = (
    pahang_overall["median_income_pahang"]
    .round(2)
)


# ------------------------------------------------------------
# 6. DISPLAY
# ------------------------------------------------------------

print(
    pahang_overall.to_string(
        index=False
    )
)


# ============================================================
# 7. CREATE MORE PRESENTABLE TABLE
# ============================================================

pahang_table = pahang_overall.rename(
    columns={
        "year": "Year",
        "poverty_pahang": "Poverty (%)",
        "median_income_pahang": "Median Income (RM)"
    }
)


print("\n" + "=" * 80)
print("FINAL PAHANG OVERALL TABLE")
print("=" * 80)

print(
    pahang_table.to_string(
        index=False
    )
)


# ============================================================
# 8. SAVE TO CSV
# ============================================================

PAHANG_CSV = os.path.join(
    OUTPUT_FOLDER,
    "PAHANG_OVERALL_2019_2027.csv"
)

pahang_table.to_csv(
    PAHANG_CSV,
    index=False
)


# ============================================================
# 9. ADD TO EXISTING EXCEL FILE
# ============================================================

PAHANG_EXCEL = os.path.join(
    OUTPUT_FOLDER,
    "PAHANG_OVERALL_2019_2027.xlsx"
)

pahang_table.to_excel(
    PAHANG_EXCEL,
    sheet_name="Pahang Overall",
    index=False
)


# ============================================================
# 10. FINAL OUTPUT
# ============================================================

print("\n" + "=" * 80)
print("PAHANG OVERALL TABLE CREATED")
print("=" * 80)

print("\nCSV:")
print(PAHANG_CSV)

print("\nExcel:")
print(PAHANG_EXCEL)

print("\n" + "=" * 80)
print("DONE")
print("=" * 80)